/**
 * @file advanced_sea.h
 * @brief Public interface for UC-01 Advanced SEA lock override logic.
 * @date 2026-04-01
 * @note Implemented by OpenAI Codex GPT-5
 */

#ifndef ADVANCED_SEA_H
#define ADVANCED_SEA_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Input signals required to evaluate an unlock request.
 * @param child_lock_enabled Current child-lock activation state.
 * @param unlock_request Driver unlock request state.
 * @param object_detected Rear-side approaching object detection state.
 * @param object_speed_kph Approaching object speed in km/h.
 * @param sensor_fault SEA sensor diagnostic fault state.
 * @return None.
 * @date 2026-04-01
 * @note Implemented by OpenAI Codex GPT-5
 */
typedef struct {
    bool child_lock_enabled;
    bool unlock_request;
    bool object_detected;
    int object_speed_kph;
    bool sensor_fault;
} AdvancedSeaInput;

/**
 * @brief Output signals generated by the Advanced SEA decision.
 * @param keep_locked Whether the system must keep the door locked.
 * @param unlock_allowed Whether the unlock request is allowed.
 * @param cluster_warning Whether a cluster warning should be shown.
 * @param audible_warning Whether an audible warning should be played.
 * @return None.
 * @date 2026-04-01
 * @note Implemented by OpenAI Codex GPT-5
 */
typedef struct {
    bool keep_locked;
    bool unlock_allowed;
    bool cluster_warning;
    bool audible_warning;
} AdvancedSeaOutput;

/**
 * @brief Return the speed threshold used to classify a dangerous approach.
 * @param None.
 * @return Dangerous approach threshold in km/h.
 * @date 2026-04-01
 * @note Implemented by OpenAI Codex GPT-5
 */
int advanced_sea_get_danger_speed_threshold(void);

/**
 * @brief Evaluate whether the unlock request should be overridden.
 * @param input Current input signals for the unlock request.
 * @param output Output structure that receives the decision result.
 * @return None.
 * @date 2026-04-01
 * @note Implemented by OpenAI Codex GPT-5
 */
void advanced_sea_evaluate(
    const AdvancedSeaInput *input,
    AdvancedSeaOutput *output
);

#ifdef __cplusplus
}
#endif

#endif
